version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab
    ports:
      - "10080:10080"
      - "5005:5005"
    volumes:
      - "./gitlab/etc:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
  runner:
    image: gitlab/gitlab-runner:latest
    hostname: runner
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./runner:/etc/gitlab-runner"
  grunt:
    hostname: grunt
    build: .
    ports:
      - "8000:8000"
